version: '3'

# #####################
# VOLUMES
# #####################

volumes:
  jwt_tokens:
    driver: local
  rabbitdata:
    driver: local
  sqldata:
    driver: local
  graphdata:
    driver: local
  mongodata:
    driver: local
  pureftpd:
    driver: local
  letsencrypt_certs:
    driver: local
  ssl_dhparam:
    driver: local

  # redisdata:
  #   driver: local

# #####################
# NETWORKS
# #####################

networks:
  # default:
  i_net:
  app_net:
  proxy_net:
  worker_net:
  ftp_net:
  db_net:
    # # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     # Note: use this configuration to match inside internal rules
    #     # TOFIX: make this an env variable
    #     - subnet: ${DB_SUBNET}/16

# #####################
# SERVICES
# #####################
services:

  ########################
  ###  MAIN CONTAINER  ###
  ########################
  backend:
    # command: sleep infinity
    build:
      context: ${SUBMODULE_DIR}/build-templates/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}

    # image: ${COMPOSE_PROJECT_NAME}/backend:template
    image: rapydo/backend:${RAPYDO_VERSION}
    # hostname: restapi
    hostname: rapydo_server
    environment:
      ACTIVATE: 0  # activate me inside your Blueprint
      # FLASK_APP: ${COMPOSE_PROJECT_NAME}/${PYTHON_MAIN_FILE}.py
      # UWSGI_APP: ${COMPOSE_PROJECT_NAME}.${PYTHON_MAIN_FILE}
      FLASK_APP: ${PYTHON_PATH}/restapi/${PYTHON_MAIN_FILE}.py
      UWSGI_APP: restapi.${PYTHON_MAIN_FILE}
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
      # enable the basic /api/login method
      MAIN_LOGIN_ENABLE: 1
      # base the user/role mechanism on some database
      AUTH_ENABLE: 0
      # AUTH_SERVICE: ${AUTH_SERVICE}
      DEBUG_ENDPOINTS: 0
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/rapydo-confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/project_configuration.yaml:/code/confs/project_configuration.yaml
      # Vanilla code
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/backend:/code/${COMPOSE_PROJECT_NAME}
      # JWT tokens secret
      - jwt_tokens:${JWT_APP_SECRETS}
    networks:
      app_net:
        aliases:
          - ${FLASK_HOST}
      db_net:
      # i_net:
    # privileged: ${DOCKER_PRIVILEGED_MODE}

  ##############################
  proxy:
    build:
      context: ${SUBMODULE_DIR}/build-templates/proxy
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/proxy:${RAPYDO_VERSION}
    hostname: reverseproxy
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - ssl_dhparam:/etc/nginx/ssl/
    networks:
      proxy_net:
        aliases:
          - ${PROXY_HOST}
      app_net:
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL
    environment:
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}
      ACTIVATE: 0
    depends_on:
      # NOTE: you have to rewrite all depends_on in a new yml file
      # at the moment they do not cumulate
      - backend
      # - frontend

  ###################
  ###  DATABASES  ###
  ###################
  postgres:
    # image: postgres:9.6.5-alpine
    image: postgres:10.0-alpine
    volumes:
      - sqldata:/var/lib/postgresql/data
      - ${SUBMODULE_DIR}/build-templates/postgres/pgs_init.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh:ro
    environment:
      ACTIVATE: 0
      POSTGRES_USER: "${PLACEHOLDER}"
      POSTGRES_PASSWORD: "${PLACEHOLDER}"
      POSTGRES_DBS: ${PLACEHOLDER}
    networks:
      db_net:
        aliases:
          - ${ALCHEMY_HOST}

  neo4j:
    image: neo4j:3.3.2
    volumes:
      - graphdata:/data
    networks:
      db_net:
        aliases:
          - ${GRAPHDB_HOST}
    environment:
      ACTIVATE: 0
      NEO4J_AUTH: neo4j/${PLACEHOLDER}
      # NEO4J_dbms_memory_pagecache_size: 2048M
      # NEO4J_dbms_memory_heap_maxSize: 4096M
    # ports:
    #   - 9090:7474
    #   - 7687:7687

  mongodb:
    image: mongo:3.4
    volumes:
      - mongodata:/data/db
    networks:
      db_net:
        aliases:
          - ${MONGO_HOST}
    environment:
      ACTIVATE: 0

  #########################
  ###  QUEUE MANAGEMENT ###
  #########################

  celery:
    build:
      context: ${SUBMODULE_DIR}/build-templates/celery
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    # image: ${COMPOSE_PROJECT_NAME}/celery:template
    image: rapydo/celery:${RAPYDO_VERSION}
    # hostname: celworker
    # command: celery worker -c 1 -A rapydo.flask_ext.flask_celery.worker.celery_app
    user: root
    working_dir: /code
    environment:
      ACTIVATE: 0
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/rapydo-confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/project_configuration.yaml:/code/confs/project_configuration.yaml
      # Vanilla code
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/backend:/code/${COMPOSE_PROJECT_NAME}
      # JWT tokens secret
      - jwt_tokens:${JWT_APP_SECRETS}
    networks:
      db_net:
      worker_net:
    depends_on:
      - rabbit
      # - celeryui

  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      worker_net:
        aliases:
          - ${CELERY_BROKER_HOST}
    environment:
      ACTIVATE: 0

  ##########################
  ### SERVICE INTERFACES ###
  ##########################

  celeryui:
    build:
      context: ${SUBMODULE_DIR}/build-templates/celery
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    # image: ${COMPOSE_PROJECT_NAME}/celery:template
    image: rapydo/celery:${RAPYDO_VERSION}
    hostname: flower
    user: root
    working_dir: /code
    command: start_flower
    expose:
      - 5555
    ports:
      - 5555:5555
    environment:
      ACTIVATE: 0
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/rapydo-confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/project_configuration.yaml:/code/confs/project_configuration.yaml
      # Vanilla code
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/backend:/code/${COMPOSE_PROJECT_NAME}
      # JWT tokens secret
      - jwt_tokens:${JWT_APP_SECRETS}
    networks:
      db_net:
      worker_net:
    depends_on:
      - rabbit

  swaggerui:
    # build: ${SUBMODULE_DIR}/build-templates/swaggerui
    image: swaggerapi/swagger-ui:latest
    # image: swaggerapi/swagger-ui:v3.0.5
    environment:
      ACTIVATE: 0

  sqlalchemyui:
    # build: ${SUBMODULE_DIR}/build-templates/sqlalchemyui
    image: adminer:4.3.1-standalone
    # NOTE: this image let you access sqllite/postgres/mysql
    # with a phpmyadmin-like web page
    networks:
      db_net:
    environment:
      ACTIVATE: 0
      # https://github.com/vrana/adminer/tree/master/designs
      # ADMINER_DESIGN: brade

  mongoui:
    image: mongo-express:0.40.0
    environment:
      ACTIVATE: 0
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
    networks:
      db_net:

  #############
  # REST API client (wget, curl, httpie, http-prompt)
  restclient:
    build:
      context: ${SUBMODULE_DIR}/build-templates/restclient
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    # image: ${COMPOSE_PROJECT_NAME}/restclient:template
    image: rapydo/restclient:${RAPYDO_VERSION}
    hostname: rapydo_client
    environment:
      MAIN_ENDPOINT: ${API_MAIN_ENDPOINT}
      ACTIVATE: 0
    volumes:
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/project_configuration.yaml:/code/custom.yml
      # - ${SUBMODULE_DIR}/rapydo-confs/projects_defaults.yaml:/code/base.yml


  ###################
  ### FTP SERVER  ###
  ###################
  ftp:
    # image: stilliard/pure-ftpd:latest
    build: ${SUBMODULE_DIR}/build-templates/ftp
    # image: ${COMPOSE_PROJECT_NAME}/ftp:template
    image: rapydo/ftp:${RAPYDO_VERSION}
    volumes:
      - pureftpd:/etc/pure-ftpd/passwd
  # /etc/ssl/private/ A directory containing a single pure-ftpd.pem file
  # with the server's SSL certificates for TLS support. Optional TLS is
  # automatically enabled when the container finds this file on startup.
    environment:
      ACTIVATE: 0
      PUBLICHOST: ${PROJECT_DOMAIN}
      ADDED_FLAGS: -d -d
    networks:
      ftp_net:

  ######################################################
  ###  iRODS iCAT server (usually for EUDAT B2safe)  ###
  ######################################################
  icat:
    # B2safe instance on irods
    build:
      context: ${SUBMODULE_DIR}/build-templates/icat
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/icat:${RAPYDO_VERSION}
    hostname: ${IRODS_HOST}
    # command: sleep infinity
    environment:
      ACTIVATE: 0
      POSTGRES_HOST: ${PLACEHOLDER}
      POSTGRES_USER: ${PLACEHOLDER}
      POSTGRES_PASSWORD: ${PLACEHOLDER}
      IRODS_HOST: ${PLACEHOLDER}
      IRODS_PORT: ${PLACEHOLDER}
      IRODS_ZONE: ${PLACEHOLDER}
      IRODS_DB: ${PLACEHOLDER}
      IRODS_USER: ${PLACEHOLDER}
      IRODS_PASSWORD: ${PLACEHOLDER}
    networks:
      i_net:
        aliases:
          - ${IRODS_HOST}
      db_net:
    depends_on:
      - postgres

  # #################################
  # OTHERS
  # #################################

  #######################
  # elasticsearch:
  #   image: elasticsearch
  #   hostname: elastic
  #   volumes:
  #       - restangulask_graphbased_elasticdata:/usr/share/elasticsearch/data

  #################################
  # REDIS key/value store
  # redisqueue:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   hostname: myqueue
  #   volumes:
  #     - redisdata:/data
